name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, master]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  review:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      max-parallel: 1
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Compute DIFF SHAs
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE="${{ github.event.pull_request.base.sha }}"
            HEAD="${{ github.sha }}"
          else
            BEFORE="${{ github.event.before }}"
            if [ -z "$BEFORE" ] || [ "$BEFORE" = "0000000000000000000000000000000000000000" ]; then
              if git rev-parse HEAD~1 >/dev/null 2>&1; then
                BASE="$(git rev-parse HEAD~1)"
              else
                BASE="${{ github.sha }}"
              fi
            else
              BASE="$BEFORE"
            fi
            HEAD="${{ github.sha }}"
          fi
          echo "BASE=$BASE" >> "$GITHUB_ENV"
          echo "HEAD=$HEAD" >> "$GITHUB_ENV"
          echo "Using BASE=$BASE HEAD=$HEAD"

      - name: Preflight secrets & API (OpenAI or HF)
        if: ${{ github.event_name == 'pull_request' }}
        env:
          # OpenAI
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
          # Hugging Face
          HF_API_KEY:   ${{ secrets.HF_API_KEY }}
          HF_API_BASE:  ${{ secrets.HF_API_BASE }}
          HF_MODEL:     ${{ vars.HF_MODEL }}
        shell: bash
        run: |
          set -e
          has_openai=0
          has_hf=0

          if [ -n "${OPENAI_API_KEY}" ]; then
            has_openai=1
          fi
          if [ -n "${HF_API_KEY}" ] && { [ -n "${HF_MODEL}" ] || [ -n "${HF_API_BASE}" ]; }; then
            has_hf=1
          fi

          if [ "$has_openai" -eq 0 ] && [ "$has_hf" -eq 0 ]; then
            echo "::warning::No provider configured (need OPENAI_* or HF_API_KEY + HF_MODEL/HF_API_BASE). Skipping AI review."
            echo "SKIP_AI_REVIEW=1" >> "$GITHUB_ENV"
            exit 0
          fi

          # Optional quick ping for whichever provider is present (don’t fail the job if it 4xx/5xx)
          if [ "$has_openai" -eq 1 ]; then
            BASE_URL="${OPENAI_BASE_URL:-https://api.openai.com/v1}"
            echo "Preflight: OpenAI present → $BASE_URL"
            curl -sS "$BASE_URL/models" \
              -H "Authorization: Bearer $OPENAI_API_KEY" \
              -H "Content-Type: application/json" | head -n 3 || true
          fi

          if [ "$has_hf" -eq 1 ]; then
            # If HF_API_BASE not given, derive it from HF_MODEL for logging only
            if [ -z "${HF_API_BASE}" ] && [ -n "${HF_MODEL}" ]; then
              HF_API_BASE="https://api-inference.huggingface.co/models/${HF_MODEL}"
            fi
            echo "Preflight: Hugging Face present → ${HF_API_BASE}"
            curl -sS -X POST "${HF_API_BASE}" \
              -H "Authorization: Bearer ${HF_API_KEY}" \
              -H "Content-Type: application/json" \
              -d '{"inputs":"ping"}' | head -n 1 || true
          fi


      - name: Debug config (no secrets printed)
        shell: bash
        env:
          OPENAI_API_KEY:         ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL:        ${{ secrets.OPENAI_BASE_URL }}
          OPENAI_MODEL:           ${{ secrets.OPENAI_MODEL || vars.OPENAI_MODEL || 'gpt-5-mini' }}
          OPENAI_TEMPERATURE:     ${{ secrets.OPENAI_TEMPERATURE || vars.OPENAI_TEMPERATURE || 0.2 }}
          OPENAI_MAX_TOKENS:      ${{ secrets.OPENAI_MAX_TOKENS || vars.OPENAI_MAX_TOKENS || 300 }}
          OPENAI_PRE_DELAY_SEC:   ${{ secrets.OPENAI_PRE_DELAY_SEC || vars.OPENAI_PRE_DELAY_SEC || 5 }}
          OPENAI_INTER_CALL_DELAY_SEC: ${{ secrets.OPENAI_INTER_CALL_DELAY_SEC || vars.OPENAI_INTER_CALL_DELAY_SEC || 25 }}
          OPENAI_MAX_ATTEMPTS:    ${{ secrets.OPENAI_MAX_ATTEMPTS || vars.OPENAI_MAX_ATTEMPTS || 6 }}
          OPENAI_BACKOFF_CAP_SEC: ${{ secrets.OPENAI_BACKOFF_CAP_SEC || vars.OPENAI_BACKOFF_CAP_SEC || 60 }}
          CHARS_PER_CHUNK:        ${{ secrets.CHARS_PER_CHUNK || vars.CHARS_PER_CHUNK || 500 }}
          LLM_BATCH_SIZE:         ${{ secrets.LLM_BATCH_SIZE || vars.LLM_BATCH_SIZE || 1 }}
          REVIEW_CACHE_TTL_SEC:   ${{ secrets.REVIEW_CACHE_TTL_SEC || vars.REVIEW_CACHE_TTL_SEC || 86400 }}
        run: |
          echo "MODEL=${OPENAI_MODEL:-unset}"
          echo "BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}"
          for v in OPENAI_MAX_TOKENS OPENAI_TEMPERATURE OPENAI_MAX_ATTEMPTS OPENAI_BACKOFF_CAP_SEC OPENAI_INTER_CALL_DELAY_SEC OPENAI_PRE_DELAY_SEC CHARS_PER_CHUNK LLM_BATCH_SIZE REVIEW_CACHE_TTL_SEC; do
            if [ -n "${!v}" ]; then echo "$v=set"; else echo "$v=EMPTY"; fi
          done
      
      
      - name: Debug LLM provider env
        run: |
          echo "HF_API_KEY: ${{ secrets.HF_API_KEY != '' && 'set' || 'empty' }}"
          echo "HF_API_BASE: ${{ secrets.HF_API_BASE }}"
          echo "LLM_API_KEY: ${{ env.LLM_API_KEY != '' && 'set' || 'empty' }}"
          echo "LLM_API_BASE: ${{ env.LLM_API_BASE }}"
          echo "OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY != '' && 'set' || 'empty' }}"
          echo "OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL || 'unset' }}"


      - name: Run AI reviewer
        if: ${{ github.event_name == 'pull_request' && env.SKIP_AI_REVIEW != '1' }}
        continue-on-error: true
        env:
          # Hugging Face (preferred when present)
          HF_API_KEY:   ${{ secrets.HF_API_KEY }}
          HF_API_BASE:  ${{ secrets.HF_API_BASE }}     # leave empty if using HF_MODEL
          HF_MODEL:     ${{ vars.HF_MODEL }}           # e.g. HuggingFaceH4/zephyr-7b-beta

          # OpenAI (fallback)
          OPENAI_API_KEY:         ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL:        ${{ secrets.OPENAI_BASE_URL }}
          OPENAI_MODEL:           ${{ secrets.OPENAI_MODEL || vars.OPENAI_MODEL || 'gpt-5-mini' }}

          # Tuning
          OPENAI_TEMPERATURE:     0.2
          OPENAI_MAX_TOKENS:      300
          OPENAI_PRE_DELAY_SEC:   3
          OPENAI_INTER_CALL_DELAY_SEC: 10
          OPENAI_MAX_ATTEMPTS:    6
          OPENAI_BACKOFF_CAP_SEC: 60

          # Chunking + cache
          CHARS_PER_CHUNK:        1000
          LLM_BATCH_SIZE:         1
          REVIEW_CACHE_TTL_SEC:   86400
          REVIEW_CACHE_BUSTER:    ${{ vars.REVIEW_CACHE_BUSTER || '' }}

          PYTHONUNBUFFERED: "1"
        run: |
          set -e
          timeout 300 python -u -m src.reviewer --base "$BASE" --head "$HEAD" || \
            echo "::warning::AI reviewer exceeded time or failed. Report may be partial."



      - name: Upload review report (artifact)
        if: ${{ github.event_name == 'pull_request' && env.SKIP_AI_REVIEW != '1' }}
        uses: actions/upload-artifact@v4
        with:
          name: ai_review_report
          path: ai_review_report.md
          if-no-files-found: warn

      - name: Run Git Insights (generate insights.json)
        if: ${{ github.event_name == 'pull_request' }}
        run: python -m project.cli --limit 100 --out insights.json || echo "Git Insights failed"

      - name: Upload Git Insights (artifact)
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: git_insights
          path: insights.json
          if-no-files-found: warn

      - name: Verify report & PR number
        if: ${{ github.event_name == 'pull_request' && env.SKIP_AI_REVIEW != '1' }}
        shell: bash
        run: |
          echo "PR=${{ github.event.pull_request.number }}"
          if [ -f ai_review_report.md ]; then
            echo "Report bytes: $(wc -c < ai_review_report.md)"
          else
            echo "MISSING ai_review_report.md"
          fi

      - name: Prepare AI review comment body
        if: ${{ github.event_name == 'pull_request' && env.SKIP_AI_REVIEW != '1' }}
        run: |
          echo "<!-- ai-review-report -->" > comment.md
          cat ai_review_report.md >> comment.md

      - name: Find existing AI review comment
        if: ${{ github.event_name == 'pull_request' && env.SKIP_AI_REVIEW != '1' }}
        id: find_comment
        uses: peter-evans/find-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '<!-- ai-review-report -->'

      - name: Create or update AI review comment
        if: ${{ github.event_name == 'pull_request' && env.SKIP_AI_REVIEW != '1' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: comment.md
          edit-mode: replace
