name: AI Code Review (Gemini)

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Find BASE/HEAD
        id: range
        run: |
          echo "BASE=$(jq -r '.pull_request.base.sha // ""' "$GITHUB_EVENT_PATH")" >> $GITHUB_OUTPUT
          echo "HEAD=$(jq -r '.pull_request.head.sha // env.GITHUB_SHA' "$GITHUB_EVENT_PATH")" >> $GITHUB_OUTPUT

      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - run: pip install -r requirements.txt

      - name: Run reviewer (calculator only)
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL:   ${{ vars.GEMINI_MODEL || 'gemini-2.5-flash' }}
        run: |
          python -u src/reviewer.py \
            --base ${{ steps.range.outputs.BASE }} \
            --head ${{ steps.range.outputs.HEAD }} \
            --path "src/calculator.py"

      - name: Upload review report
        uses: actions/upload-artifact@v4
        with:
          name: ai_review_report
          path: ai_review_report.md

      - name: Comment review on PR
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "<!-- ai-review-report -->" > comment.md
          cat ai_review_report.md >> comment.md
        shell: bash
      - uses: peter-evans/find-comment@v3
        if: ${{ github.event_name == 'pull_request' }}
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '<!-- ai-review-report -->'
      - uses: peter-evans/create-or-update-comment@v4
        if: ${{ github.event_name == 'pull_request' }}
        with:
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: comment.md
          edit-mode: replace
